{
  "Version":"2012-10-17",
  "Statement":[
    {
      "Action":[
        "iam:PassRole"
      ],
      "Resource": [
        "*"
      ],
      "Effect":"Allow",
      "Condition":{
        "StringEqualsIfExists":{
          "iam:PassedToService":[
            "ecs-tasks.amazonaws.com"
          ]
        }
      }
    },
    {
      "Action":[
        "codecommit:CancelUploadArchive",
        "codecommit:GetBranch",
        "codecommit:GetCommit",
        "codecommit:GetUploadArchiveStatus",
        "codecommit:UploadArchive"
      ],
      "Resource":"*",
      "Effect":"Allow"
    },
    {
      "Action":[
        "codedeploy:CreateDeployment",
        "codedeploy:GetApplication",
        "codedeploy:GetApplicationRevision",
        "codedeploy:GetDeployment",
        "codedeploy:GetDeploymentConfig",
        "codedeploy:RegisterApplicationRevision"
      ],
      "Resource":"*",
      "Effect":"Allow"
    },
    {
      "Action":[
        "ec2:*",
        "elasticloadbalancing:*",
        "autoscaling:*",
        "cloudwatch:*",
        "s3:*",
        "sns:*",
        "ecs:*"
      ],
      "Resource":"*",
      "Effect":"Allow"
    },
    {
      "Action":[
        "lambda:InvokeFunction",
        "lambda:ListFunctions"
      ],
      "Resource":"*",
      "Effect":"Allow"
    },
    {
      "Action":[
        "codebuild:BatchGetBuilds",
        "codebuild:StartBuild"
      ],
      "Resource":"*",
      "Effect":"Allow"
    },
    {
      "Effect":"Allow",
      "Action":[
        "ecr:DescribeImages"
      ],
      "Resource":"*"
    }
  ]
}
